### PR TITLE
Implement loading responses from data/

### PR DESCRIPTION
**Pull request by spycrab**
*New environment variables*
- `DATA_CUSTOM_RESPONSES`: Whether or not to load responses.js from the data directory.

This makes the discord-bot load its `responses.json` from the `data` instead of the `src` directory.

### CODE REVIEW

**Comment by JayFoxRox** [comment]
Please provide a description for this change.
I think this is supposed to handle seperation of yuzu- and citrabot configs by providing a config path?

If so, is this only the first part of a larger change?

I think it would also be more useful to have the citrabot config in a different repo on citra-emu, the yuzubot config in a repo on yuzu-emu and then provide an option to select the config path or submodule the config.
That way we could either have both bots run from the same installation folder by selecting a different config file, or they could be ran from different folders with a different config-submodule remote.

**Comment by spycrab** [comment]
@JayFoxRox Added a description. Removing `src/responses.json` and moving it into a separate config folder sounds great though.

**Comment by JayFoxRox** [comment]
Merging this silently is a bit of bad practice in my opinion.
What was the state of the code when it was merged and how will we continue with config directories / loading?
These things should be on record so people understand why design decisions were made and don't have to look into the code to understand how to use the software.

**Comment by chris062689** [comment]
These two PRs / changes were requested due to attempting to reuse the same code between Citra and yuzu. 

As of this PR. responses.json was a hardcoded file inside the repository. 

This PR made this file loadable inside of the data directory. 

I committed a few additional commits after this for general cleanup and adding a few environmental variables. 

The documentation will be updated to reflect this in the coming days.

**Pull request merged**
