### PR TITLE
Update citra bot .apk command

### PR DESCRIPTION
**Pull request by TGP17**
This updates the .apk command, by saying to download the .apk.zip, while it previously said to download the .apk, which isn't correct anymore

### CODE REVIEW

**Comment by FearlessTobi** [comment]
I am fine with this change. However, why are we even doing this? As far as I know, apks are already zipped.

**Comment by TGP17** [comment]
> I am fine with this change. However, why are we even doing this? As far as I know, apks are already zipped.

This PR https://github.com/citra-emu/citra/pull/7045 made the change to compress the APK's Added compression to apk's to keep the download size down.

**Review by FearlessTobi — APPROVED** [review]
Turns out Google uses very bad/no compression, so zipping the .apk's is fine.

**Review by sakuramipha — APPROVED** [review]

**Comment by FearlessTobi** [comment]
We can probably revert this soon when https://github.com/citra-emu/citra/pull/7258 is merged.

**Pull request merged**
